[[section-runtime-view]]
== Vista de ejecución


=== Usuario se registra o inicia sesión

Un usuario inicia sesión o se registra en la aplicación. Desde un POD.

[plantuml,"06_runtime_registro",png]
----
actor Bob
participant DeDe
database Pod
Bob -> DeDe: goToLogIn()
DeDe -> Pod: Redirecciona el inicio de sesión al proveedor del POD
Bob <-- Pod: Pide los datos para registro/inicio sesión
Bob -> Pod: Inserta los datos
DeDe <-- Pod: Validación
Bob <-- DeDe: VueLve a la página principal pero logueado
----

=== Usuario filtra los productos
Búsqueda de artículos mediante los filtros proporcionados por la aplicación. Este caso simula que el usuario quiere ver las sudaderas.
[plantuml,"06_runtime_filtro",png]
----
actor Bob
participant DeDe
database DataBase as "DataBase"
Bob -> DeDe: Pulsa "Sudaderas": refreshProducts("Sudaderas")
DeDe-> DataBase: Pide la lista de sudaderas
DataBase --> DeDe: Devuelve la lista de sudaderas
DeDe-> DeDe: Muestra solo las sudaderas
----

=== Usuario logueado realiza un pedido
Un usuario que está en sesión realiza un pedido. Para ello añade los productos al carrito,
selecciona una de sus direcciones alamacenadas en el pod, inserta datos de la tarjeta y una API de shippment se
encarga de calcular los gatos de envío, la fecha de entrega y la URL para que el usuario pueda seguir su pedido.
Antes de confirmarlo se le mostrarán al usuario todos los datos, precios, fechas, etc.

[plantuml,"06_runtime_pedido",png]
----
actor Bob
participant DeDe
database Pod
participant ShippoAPI
database DataBase as "DataBase"
Bob-> DeDe: Sobre un producto addToCart()
DeDe-> DeDe: Añade producto al carrito
Bob -> DeDe: Abre el carrito: goToCart()
Bob <-- DeDe: Muestra vista carrito
Bob -> DeDe: pulsa Realizar pedido
Bob <-- DeDe: Muestra vista checkout
DeDe-> Pod: getAddressesFromPod()
DeDe <-- Pod: devuelve lista de direcciones del usuario
Bob -> DeDe: Selecciona dirección a la que se enviará el pedido y completa el resto de formularios
DeDe -> ShippoAPI: Envía dirección de envío
DeDe <-- ShippoAPI: Calcula gastos de envío, fecha de entrega y url de seguimiento
DeDe -> Bob: Muestra resumen del pedido
Bob -> DeDe : Confirma el pedido
DeDe -> DataBase: addOrder()
Bob <-- DeDe: Pedido realizado con éxito
----

=== Usuario se loguea para ver sus pedidos
El cliente inicia sesión para ver el listado de pedidos que ha realizado.
[plantuml,"06_runtime_verPedido",png]
----
actor Bob
participant DeDe
database Pod
database database
Bob -> DeDe: goToLogin()
DeDe -> Pod: Redirecciona al proveedor del POD
Bob <-- Pod: Pide los datos para iniciar sesión
Bob -> Pod: Inserta los datos
DeDe <-- Pod: Confirmación de datos
Bob <-- DeDe: Sesión iniciada
DeDe -> DeDe: Bob es redireccionado a la home page
Bob -> DeDe: pulsa "Mis pedidos" en la barra de navegación 
DeDe -> database: findOrdersByUser(Bob.webId)
DeDe <-- database: Devuelve los pedidos asociados al webId de Bob
Bob <-- DeDe: Muestra la vista de pedidos
----