[[section-technical-risks]]
== Risks and Technical Debts


[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.
****

.Lista de riesgos técnicos y deuda técnica
- Falta de trabajo por parte de algún/os miembro/s del equipo, y en una situación extrema, el abandono por su parte del equipo.
- Conocimiento límitado del lenguaje y las herramientas tecnológicas a utilizar para el desarrollo de la aplicación.
- Poner en riesgo el trabajo de los demás a la hora de mezclar las partes sin el consentimiento de los compañeros.
- Fallos en la comunicación, tanto en el grupo de desarrollo como con el cliente.
- Mala planificación, o estimaciones poco realistas.
- No tener un código cohesivo, sin acoplamiento, refactorizado y enfocado al cambio.
